# Generated by Django 2.2 on 2019-04-14 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20190414_0735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='image',
            new_name='file',
        ),
    ]
